import { DogBreed } from "@/types/dogmatch";

export const mockBreeds: DogBreed[] = [
  {
    id: "1",
    name: "Golden Retriever",
    size: "Large",
    exerciseNeeds: 3,
    goodWithChildren: true,
    intelligence: 9,
    trainingDifficulty: 3,
    shedding: "High",
    healthRisk: "Medium",
    breedGroup: "Sporting",
    friendliness: 10,
    lifeExpectancy: 12,
    averageWeight: 32,
    description: "Uma raça amigável, inteligente e devotada. Perfeita para famílias.",
    temperament: ["Amigável", "Inteligente", "Devotado", "Confiável"],
    care: ["Escovação regular", "Exercício diário", "Socialização"],
    history: "Originários da Escócia no século XIX, foram criados para recuperar aves aquáticas.",
    images: ["https://images.unsplash.com/photo-1633722715463-d30f4f325e24"]
  },
  {
    id: "2",
    name: "Labrador Retriever",
    size: "Large",
    exerciseNeeds: 3.5,
    goodWithChildren: true,
    intelligence: 9,
    trainingDifficulty: 2,
    shedding: "High",
    healthRisk: "Medium",
    breedGroup: "Sporting",
    friendliness: 10,
    lifeExpectancy: 12,
    averageWeight: 32,
    description: "Extremamente amigável e enérgico, ideal para famílias ativas.",
    temperament: ["Amigável", "Ativo", "Sociável", "Leal"],
    care: ["Exercício abundante", "Treinamento consistente", "Escovação semanal"],
    history: "Originários da Terra Nova, Canadá, foram cães de trabalho de pescadores.",
    images: ["https://images.unsplash.com/photo-1579143570024-93a2b1b99cad"]
  },
  {
    id: "3",
    name: "Beagle",
    size: "Medium",
    exerciseNeeds: 2.5,
    goodWithChildren: true,
    intelligence: 7,
    trainingDifficulty: 6,
    shedding: "Moderate",
    healthRisk: "Low",
    breedGroup: "Hound",
    friendliness: 9,
    lifeExpectancy: 13,
    averageWeight: 12,
    description: "Alegre, curioso e ótimo com crianças. Perfeito para famílias.",
    temperament: ["Alegre", "Curioso", "Amigável", "Determinado"],
    care: ["Exercício moderado", "Treinamento de obediência", "Verificações de orelha"],
    history: "Raça antiga de caça inglesa, conhecida por seu olfato excepcional.",
    images: ["https://images.unsplash.com/photo-1505628346881-b72b27e84530"]
  },
  {
    id: "4",
    name: "Poodle",
    size: "Medium",
    exerciseNeeds: 2,
    goodWithChildren: true,
    intelligence: 10,
    trainingDifficulty: 2,
    shedding: "Low",
    healthRisk: "Medium",
    breedGroup: "Non-Sporting",
    friendliness: 8,
    lifeExpectancy: 14,
    averageWeight: 23,
    description: "Inteligente, elegante e hipoalergênico. Excelente para treino.",
    temperament: ["Inteligente", "Ativo", "Orgulhoso", "Treinável"],
    care: ["Tosa regular", "Estimulação mental", "Exercício diário"],
    history: "Originalmente da Alemanha como cão de caça aquática, refinado na França.",
    images: ["https://images.unsplash.com/photo-1537151608828-ea2b11777ee8"]
  },
  {
    id: "5",
    name: "Border Collie",
    size: "Medium",
    exerciseNeeds: 4,
    goodWithChildren: true,
    intelligence: 10,
    trainingDifficulty: 2,
    shedding: "Moderate",
    healthRisk: "Low",
    breedGroup: "Herding",
    friendliness: 7,
    lifeExpectancy: 14,
    averageWeight: 18,
    description: "O cão mais inteligente. Requer muita estimulação mental e física.",
    temperament: ["Inteligente", "Enérgico", "Alerta", "Trabalhador"],
    care: ["Exercício intenso", "Desafios mentais", "Treinamento avançado"],
    history: "Desenvolvido na fronteira anglo-escocesa para pastorear ovelhas.",
    images: ["https://images.unsplash.com/photo-1516371535707-512a1e83bb9a"]
  },
  {
    id: "6",
    name: "Bulldog Francês",
    size: "Small",
    exerciseNeeds: 1,
    goodWithChildren: true,
    intelligence: 6,
    trainingDifficulty: 7,
    shedding: "Moderate",
    healthRisk: "High",
    breedGroup: "Non-Sporting",
    friendliness: 9,
    lifeExpectancy: 11,
    averageWeight: 11,
    description: "Compacto, carismático e adaptável. Perfeito para apartamentos.",
    temperament: ["Afetuoso", "Calmo", "Sociável", "Paciente"],
    care: ["Exercício leve", "Cuidados com temperatura", "Limpeza de dobras"],
    history: "Criado na Inglaterra, popularizado na França como cão de companhia.",
    images: ["https://images.unsplash.com/photo-1583511655857-d19b40a7a54e"]
  }
];
